package com.ravi.common;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

public class TVLinks {

	public static String[] tvLinks = {
			"N/A;Star Movies;rtmp://livemedia.hayhaytv.vn:1935/hayhaytv_live,mp4:star.movie.360p",
			"N/A;HBO;rtmp://livemedia.hayhaytv.vn:1935/hayhaytv_live,mp4:hbo.360p",
			"N/A;Star Gold;http://fw01.livem3u8.me.totiptv.com/live//53c2bf7e52a44fd8b6df7f9e83891bbc.m3u8?bitrate=800",
			"N/A;Fox Movies;rtmp://iliketvhd3.dyndns.tv/live/hd_foxpe.stream",
			"N/A;Fox Crime USA;http://fw01.livem3u8.me.totiptv.com/live//5028f7ff1d1b4d5f8189690233364737.m3u8?bitrate=800",
			"N/A;Sky Sports;rtmp://173.1.41.227:1935/live/skysp2",
			"N/A;Channel V;http://fw01.livem3u8.me.totiptv.com/live//9e38a0084e6d45d080139a166c60a102.m3u8?bitrate=800",
			"N/A;Star Gold;http://fw01.livem3u8.me.totiptv.com/live//53c2bf7e52a44fd8b6df7f9e83891bbc.m3u8?bitrate=800",
			"N/A;Star Plus;http://fw01.livem3u8.me.totiptv.com/live//7c75ad89c1cc417aa0f066133c0a2333.m3u8?bitrate=800",
			"N/A;UTV Bindass;http://live.nwk.yuppcdn.net/nwk/zeetelpacific/playlist.m3u8",
//			"N/A;B4U Live Music Streaming;rtsp://46.249.213.87:554/playlists/b4u_qcif.hpl.3gp",
//			"N/A;B4U-1 Live Streaming;rtsp://59.162.166.216:554/SONYTV_QVGA.sdp",
//			"N/A;Sony Sab Live Tv Streaming;rtsp://46.249.213.93:554/playlists/sonysabtv_qcif.hpl.3gp",
//			"N/A;Etv Urdu Live Streaming;rtsp://121.241.249.136:1935/livefeed/ETVURDU_QVGA.sdp",
//			"N/A;Star Gold Live Streaming;rtsp://59.162.166.216:554/SONYTV_QVGA.sdp",
//			"N/A;FOX TV Live Streaming;rtsp://184.22.182.186/wl/channel/aaj01",
//			"N/A;Zoom ;rtsp://cdn.m.yuppcdn.net/liveorigin/zoomtv2",
//			"N/A;Zoom -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/zoomtv1",
//			"N/A;9X Jalwa-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/9xjalwa1",
//			"N/A;9X Jalwa-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/9xjalwa1",
//			"N/A;9xJhakaas-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/etvuk1",
//			"N/A;9xTashan-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/etvpacific1",
//			"N/A;9xTashan-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/etvpacific1",
//			"N/A;YupptvLive-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive3",
//			"N/A;YupptvLive-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive3",
//			"N/A;Zoom -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/zoomtv3",
//			"N/A;9X Jalwa-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/9xjalwa3",
//			"N/A;9X Jalwa-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/9xjalwa3",
//			"N/A;9xJhakaas-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/etvuk3",
//			"N/A;9X Jalwa;rtsp://cdn.m.yuppcdn.net/liveorigin/9xjalwa2",
//			"N/A;9X Jalwa;rtsp://cdn.m.yuppcdn.net/liveorigin/9xjalwa2",
//			"N/A;9xJhakaas;rtsp://cdn.m.yuppcdn.net/liveorigin/etvuk2",
//			"N/A;9xTashan;rtsp://cdn.m.yuppcdn.net/liveorigin/etvpacific2",
//			"N/A;9xTashan;rtsp://cdn.m.yuppcdn.net/liveorigin/etvpacific2",
//			"N/A;9xTashan-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/etvpacific3",
//			"N/A;9xTashan-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/etvpacific3",
//			"N/A;Aajtak;rtsp://cdn.m.yuppcdn.net/liveorigin/aajtak2",
//			"N/A;Aajtak-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/aajtak1",
//			"N/A;Aajtak-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/aajtak3",
//			"N/A;ABN Andhra Jyothi;rtsp://cdn.m.yuppcdn.net/liveorigin/abn2",
//			"N/A;ABN Andhra Jyothi -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/abn1",
//			"N/A;ABN Andhra Jyothi -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/abn3",
//			"N/A;Aradana TV;rtsp://cdn.m.yuppcdn.net/liveorigin/aradana2",
//			"N/A;Aradana TV-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/aradana1",
//			"N/A;Aradana TV-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/aradana3",
//			"N/A;asianetnews;rtsp://cdn.m.yuppcdn.net/liveorigin/asianet2",
//			"N/A;asianetnews-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/asianet1",
//			"N/A;asianetnews-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/asianet3",
//			"N/A;ATA Event;rtsp://cdn.m.yuppcdn.net/liveorigin/ata2",
//			"N/A;ATA Event-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/ata1",
//			"N/A;ATA Event-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/ata3",
//			"N/A;Atlanta Live;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive2",
//			"N/A;Atlanta Live-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive1",
//			"N/A;Atlanta Live-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive3",
//			"N/A;Bakthi;rtsp://cdn.m.yuppcdn.net/liveorigin/bhakti9002",
//			"N/A;Bakthi-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/bhakti9001",
//			"N/A;Bakthi-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/bhakti9003",
//			"N/A;Calvary TV;rtsp://cdn.m.yuppcdn.net/liveorigin/calavary2",
//			"N/A;Calvary TV-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/calavary1",
//			"N/A;Calvary TV-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/calavary3",
//			"N/A;Chardikla TIME TV;rtsp://cdn.m.yuppcdn.net/liveorigin/chardikla2",
//			"N/A;Chardikla TIME TV-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/chardikla1",
//			"N/A;Chardikla TIME TV-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/chardikla3",
//			"N/A;COMSAT TV7 HEALTH PLANET;rtsp://cdn.m.yuppcdn.net/liveorigin/tv7hp2",
//			"N/A;COMSAT TV7 HEALTH PLANET-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/tv7hp1",
//			"N/A;COMSAT TV7 HEALTH PLANET-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/tv7hp3",
//			"N/A;Dallas Live;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive2",
//			"N/A;Dallas Live-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive1",
//			"N/A;Dallas Live-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive3",
//			"N/A;Demo;rtsp://cdn.m.yuppcdn.net/liveorigin/channel39002",
//			"N/A;Demo-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel39001",
//			"N/A;Dhoom Cinema;rtsp://cdn.m.yuppcdn.net/liveorigin/dhoommovies3",
//			"N/A;Dhoom Cinema-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/dhoommovies4",
//			"N/A;Dhoom Cinema-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/dhoommovies1",
//			"N/A;DhoomMusic;rtsp://cdn.m.yuppcdn.net/liveorigin/dhoommusic9002",
//			"N/A;DhoomMusic-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/dhoommusic9001",
//			"N/A;DhoomMusic-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/dhoommusic9003",
//			"N/A;ETNow;rtsp://cdn.m.yuppcdn.net/liveorigin/etnow2",
//			"N/A;ETNow -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/etnow1",
//			"N/A;ETNow -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/etnow3",
//			"N/A;ETV2;rtsp://cdn.m.yuppcdn.net/liveorigin/etv22",
//			"N/A;ETV2-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/etv21",
//			"N/A;ETV2-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/etv23",
//			"N/A;Fun Asia;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamp2",
//			"N/A;Fun Asia Live;rtsp://cdn.m.yuppcdn.net/liveorigin/funasialive9002",
//			"N/A;Fun Asia Live-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/funasialive9001",
//			"N/A;Fun Asia-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamp1",
//			"N/A;Fun Asia-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamp3",
//			"N/A;FunasiaAM;rtsp://cdn.m.yuppcdn.net/liveorigin/funasiaam9002",
//			"N/A;FunasiaAM-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/funasiaam9001",
//			"N/A;FunasiaAM-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/funasiaam9003",
//			"N/A;Headlines Today;rtsp://cdn.m.yuppcdn.net/liveorigin/headlinetoday2",
//			"N/A;Headlines Today-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/headlinetoday1",
//			"N/A;Headlines Today-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/headlinetoday3",
//			"N/A;HMTV;rtsp://cdn.m.yuppcdn.net/liveorigin/hmtv2",
//			"N/A;HMTV -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/hmtv1",
//			"N/A;HMTV -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/hmtv3",
//			"N/A;IndiaTV;rtsp://cdn.m.yuppcdn.net/liveorigin/indiatv2",
//			"N/A;IndiaTV -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/indiatv1",
//			"N/A;IndiaTV -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/indiatv4.sdp",
//			"N/A;Jai Hind;rtsp://cdn.m.yuppcdn.net/liveorigin/jaihind2",
//			"N/A;Jai Hind-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/jaihind1",
//			"N/A;Jai Hind-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/jaihind3",
//			"N/A;Janasri News;rtsp://cdn.m.yuppcdn.net/liveorigin/channel82",
//			"N/A;Janasri News-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel81",
//			"N/A;Janasri News-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel83",
//			"N/A;Jaya Plus Tamil;rtsp://cdn.m.yuppcdn.net/liveorigin/jayaplus2",
//			"N/A;Jaya Plus Tamil-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/jayaplus1",
//			"N/A;Jaya Plus Tamil-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/jayaplus3",
//			"N/A;Jeeyar;rtsp://cdn.m.yuppcdn.net/liveorigin/kalaignar2",
//			"N/A;Jeeyar;rtsp://cdn.m.yuppcdn.net/liveorigin/kalaignar2",
//			"N/A;Jeeyar-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/kalaignar1",
//			"N/A;Jeeyar-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/kalaignar1",
//			"N/A;Jeeyar-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/kalaignar3",
//			"N/A;Jeeyar-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/kalaignar3",
//			"N/A;Kairali TV;rtsp://cdn.m.yuppcdn.net/liveorigin/kairali9002",
//			"N/A;Kairali TV-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/kairali9001",
//			"N/A;Kairali TV-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/kairali9003",
//			"N/A;Maa Gold;rtsp://cdn.m.yuppcdn.net/liveorigin/maajuniors2",
//			"N/A;Maa Gold-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/maajuniors1",
//			"N/A;Maa Music;rtsp://cdn.m.yuppcdn.net/liveorigin/maamusic1",
//			"N/A;Maa Music;rtsp://cdn.m.yuppcdn.net/liveorigin/maamusic1",
//			"N/A;Maa Music -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/maamusic",
//			"N/A;Maa Music-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/maamusic1",
//			"N/A;Maa Music-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/maamusic3",
//			"N/A;MahaaTV;rtsp://cdn.m.yuppcdn.net/liveorigin/mahatv9002",
//			"N/A;MahaaTV-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/mahatv9001",
//			"N/A;MahaaTV-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/mahatv9003",
//			"N/A;Mangalmaya;rtsp://cdn.m.yuppcdn.net/liveorigin/aasaram2",
//			"N/A;Mangalmaya-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/aasaram1",
//			"N/A;Mangalmaya-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/aasaram3",
//			"N/A;Mega 24;rtsp://cdn.m.yuppcdn.net/liveorigin/mega242",
//			"N/A;Mega 24-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/mega241",
//			"N/A;Mega 24-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/mega243",
//			"N/A;Mega Musiq;rtsp://cdn.m.yuppcdn.net/liveorigin/megamusiq2",
//			"N/A;Mega Musiq-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/megamusiq1",
//			"N/A;Mega Musiq-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/megamusiq3",
//			"N/A;Mega TV;rtsp://cdn.m.yuppcdn.net/liveorigin/megatv2",
//			"N/A;Mega TV-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/megatv1",
//			"N/A;Mega TV-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/megatv3",
//			"N/A;NATA Event;rtsp://cdn.m.yuppcdn.net/liveorigin/nata2",
//			"N/A;NATA Event-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/nata1",
//			"N/A;NATA Event-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/nata3",
//			"N/A;NDTV 24x7;rtsp://cdn.m.yuppcdn.net/liveorigin/ndtvenglish9002",
//			"N/A;NDTV 24x7-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/ndtvenglish9001",
//			"N/A;NDTV 24x7-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/ndtvenglish9003",
//			"N/A;NDTV Hindu;rtsp://cdn.m.yuppcdn.net/liveorigin/ndtvhindu9002",
//			"N/A;NDTV Hindu-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/ndtvhindu9001",
//			"N/A;NDTV Hindu-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/ndtvhindu9003",
//			"N/A;NDTV INDIA;rtsp://cdn.m.yuppcdn.net/liveorigin/ndtvhindi9002",
//			"N/A;NDTV INDIA-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/ndtvhindi9001",
//			"N/A;NDTV INDIA-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/ndtvhindi9003",
//			"N/A;newstime;rtsp://cdn.m.yuppcdn.net/liveorigin/newstimebengal9002",
//			"N/A;newstime-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/newstimebengal9001",
//			"N/A;newstime-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/newstimebengal9003",
//			"N/A;NewsX;rtsp://cdn.m.yuppcdn.net/liveorigin/newsx2",
//			"N/A;NewsX -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/newsx1",
//			"N/A;NewsX -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/newsx3",
//			"N/A;NTV;rtsp://cdn.m.yuppcdn.net/liveorigin/ntv2",
//			"N/A;NTV -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/ntv1",
//			"N/A;NTV -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/ntv3",
//			"N/A;People TV;rtsp://cdn.m.yuppcdn.net/liveorigin/people9002",
//			"N/A;People TV-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/people9001",
//			"N/A;People TV-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/people9003",
//			"N/A;PowerBlingTV;rtsp://94.75.250.53/live/c12",
//			"N/A;PowerBlingTV-High Bandwidth;rtsp://94.75.250.53/live/c11",
//			"N/A;Punjabbi TV;rtsp://cdn.m.yuppcdn.net/liveorigin/channel92",
//			"N/A;Punjabbi TV-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel91",
//			"N/A;Punjabbi TV-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel93",
//			"N/A;R K News;rtsp://cdn.m.yuppcdn.net/liveorigin/rknews2",
//			"N/A;R K News -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/rknews1",
//			"N/A;RAJ MUSIC Kannada;rtsp://cdn.m.yuppcdn.net/liveorigin/rajmusickannada2",
//			"N/A;RAJ MUSIC Kannada-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/rajmusickannada1",
//			"N/A;RAJ MUSIC Kannada-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/rajmusickannada3",
//			"N/A;Raj News;rtsp://cdn.m.yuppcdn.net/liveorigin/rajnews6002",
//			"N/A;Raj News 24X7;rtsp://cdn.m.yuppcdn.net/liveorigin/rajnewstamil2",
//			"N/A;Raj News 24X7-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/rajnewstamil1",
//			"N/A;Raj News 24X7-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/rajnewstamil3",
//			"N/A;Raj News -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/rajnews6001",
//			"N/A;Raj News -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/rajnews6003",
//			"N/A;Rakshana;rtsp://cdn.m.yuppcdn.net/liveorigin/rakshana9002",
//			"N/A;Rakshana-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/rakshana9001",
//			"N/A;Rakshana-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/rakshana9003",
//			"N/A;Rupashibangla;rtsp://cdn.m.yuppcdn.net/liveorigin/rupashibangala9002",
//			"N/A;Rupashibangla-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/rupashibangala9001",
//			"N/A;Rupashibangla-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/rupashibangala9003",
//			"N/A;S V B C;rtsp://cdn.m.yuppcdn.net/liveorigin/svbc2",
//			"N/A;S V B C -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/svbc1",
//			"N/A;Saam TV;rtsp://cdn.m.yuppcdn.net/liveorigin/channel29002",
//			"N/A;Saam TV-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel29001",
//			"N/A;Saam TV-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel29003",
//			"N/A;Sahara Aalami;rtsp://cdn.m.yuppcdn.net/liveorigin/saharaaalami2",
//			"N/A;Sahara Aalami-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharaaalami1",
//			"N/A;Sahara Aalami-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharaaalami3",
//			"N/A;Sahara Bihar;rtsp://cdn.m.yuppcdn.net/liveorigin/saharabihar2",
//			"N/A;Sahara Bihar;rtsp://cdn.m.yuppcdn.net/liveorigin/saharabihar2",
//			"N/A;Sahara Bihar-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharabihar1",
//			"N/A;Sahara Bihar-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharabihar1",
//			"N/A;Sahara Bihar-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharabihar3",
//			"N/A;Sahara Bihar-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharabihar3",
//			"N/A;Sahara Madhyapradesh;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamadhyap2",
//			"N/A;Sahara Madhyapradesh;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamadhyap2",
//			"N/A;Sahara Madhyapradesh-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamadhyap1",
//			"N/A;Sahara Madhyapradesh-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamadhyap1",
//			"N/A;Sahara Madhyapradesh-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamadhyap3",
//			"N/A;Sahara Madhyapradesh-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamadhyap3",
//			"N/A;Sahara Mumbai;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamum2",
//			"N/A;Sahara Mumbai-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamum1",
//			"N/A;Sahara Mumbai-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharamum3",
//			"N/A;Sahara NCR;rtsp://cdn.m.yuppcdn.net/liveorigin/saharah2",
//			"N/A;Sahara NCR-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharah1",
//			"N/A;Sahara NCR-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharah3",
//			"N/A;Sahara Samay;rtsp://cdn.m.yuppcdn.net/liveorigin/saharasamaynew2",
//			"N/A;Sahara Samay-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharasamaynew1",
//			"N/A;Sahara Samay-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharasamaynew3",
//			"N/A;Sahara UP;rtsp://cdn.m.yuppcdn.net/liveorigin/saharancrnew2",
//			"N/A;Sahara UP-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharancrnew1",
//			"N/A;Sahara UP-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/saharancrnew3",
//			"N/A;Sakshi TV;rtsp://cdn.m.yuppcdn.net/liveorigin/sakshi2",
//			"N/A;Sakshi TV -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/sakshi1",
//			"N/A;Sakshi TV -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/sakshi2",
//			"N/A;Songdew Live;rtsp://cdn.m.yuppcdn.net/liveorigin/songdew2",
//			"N/A;Songdew Live-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/songdew1",
//			"N/A;Songdew Live-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/songdew3",
//			"N/A;StudioN;rtsp://cdn.m.yuppcdn.net/liveorigin/studion3",
//			"N/A;StudioN -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/studion2",
//			"N/A;StudioN -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/studion4",
//			"N/A;Sudarshan News;rtsp://cdn.m.yuppcdn.net/liveorigin/sudarshantv2",
//			"N/A;Sudarshan News-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/sudarshantv1",
//			"N/A;Sudarshan News-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/sudarshantv3",
//			"N/A;Suvarna;rtsp://cdn.m.yuppcdn.net/liveorigin/suvarna2",
//			"N/A;Suvarna-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/suvarna1",
//			"N/A;Suvarna-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/suvarna3",
//			"N/A;T News;rtsp://cdn.m.yuppcdn.net/liveorigin/channel49002",
//			"N/A;T News-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel49001",
//			"N/A;Timesnow;rtsp://cdn.m.yuppcdn.net/liveorigin/timesnow2",
//			"N/A;Timesnow -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/timesnow1",
//			"N/A;Timesnow -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/timesnow3",
//			"N/A;Topper;rtsp://cdn.m.yuppcdn.net/liveorigin/channel19002",
//			"N/A;Topper-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel19001",
//			"N/A;Topper-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel19003",
//			"N/A;TV5;rtsp://cdn.m.yuppcdn.net/liveorigin/tv52",
//			"N/A;TV5 -High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/tv51",
//			"N/A;TV5 -Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/tv52",
//			"N/A;V6 News;rtsp://cdn.m.yuppcdn.net/liveorigin/v6news2",
//			"N/A;V6 News-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/v6news1",
//			"N/A;V6 News-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/v6news3",
//			"N/A;Vanitha;rtsp://cdn.m.yuppcdn.net/liveorigin/vanitha9002",
//			"N/A;Vanitha-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/vanitha9001",
//			"N/A;Vanitha-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/vanitha9003",
//			"N/A;We TV;rtsp://cdn.m.yuppcdn.net/liveorigin/we2",
//			"N/A;We TV-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/we1",
//			"N/A;We TV-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/we3",
//			"N/A;Xtra;rtsp://cdn.m.yuppcdn.net/liveorigin/channel62",
//			"N/A;Xtra-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel61",
//			"N/A;Xtra-Low Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/channel63",
//			"N/A;YupptvLive;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive2",
//			"N/A;YupptvLive;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive2",
//			"N/A;YupptvLive-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive1",
			"N/A;YupptvLive-High Bandwidth;rtsp://cdn.m.yuppcdn.net/liveorigin/yupptvlive1" };
	
	
	
	
	
	public static List<TvLink> parseTvLinks(String[] links)
	{
		List<TvLink> tvLinks = new ArrayList<TvLink>();
		for(String str : links)
		{
			String[] details = str.split(";");
			if(details.length == 3)
			{
				TvLink tvlink = new TvLink();
				tvlink.setImg(details[0]);
				tvlink.setChannelName(details[1]);
				tvlink.setChannelLink(details[2]);
				tvLinks.add(tvlink);
			}
		}
		
		Collections.sort(tvLinks, new Comparator<TvLink>() {

			@Override
			public int compare(TvLink lhs, TvLink rhs) {
				// TODO Auto-generated method stub
				return lhs.getChannelName().toLowerCase().compareTo(rhs.getChannelName().toLowerCase());
			}
		});
		
		return tvLinks;
	}
	
}
